"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.1.dev20240123084731.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

from pathlib import Path

import environs

from django.urls import reverse_lazy

import dj_database_url


env = environs.Env()
env.read_env()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = env.str("DJANGO_SECRET_KEY")
DEBUG = env.bool("DJANGO_DEBUG", default=False)
ENABLE_SILKY = env.bool("DJANGO_SILKY", default=False)

INTERNAL_IPS = env.list("DJANGO_INTERNAL_IPS", default=[])
ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=[])
CSRF_TRUSTED_ORIGINS = env.list("DJANGO_CSRF_TRUSTED_ORIGINS", default=[])

AUTH_USER_MODEL = "mysite_auth.User"
SITE_ID = 1


# Application definition

INSTALLED_APPS = [
    # Django overrides
    "mysite.auth",
    # Django core
    "django.contrib.admindocs",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Project apps
    "mysite.forms_galore",
    "mysite.library",
    "mysite.people",
    "mysite.core",
    # Third-party apps
    "django_countries",
    "phone_field",
    "django_extensions",
    "debug_toolbar",
    "silk",
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "silk.middleware.SilkyMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.contrib.admindocs.middleware.XViewMiddleware",
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "mysite.core.context_processors.current_path_processor",
                "mysite.core.context_processors.frontend_processor",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

DJANGO_DB_URL = env.str("DJANGO_DB_URL", default="") or f"sqlite:///{BASE_DIR / 'db.sqlite3'!s}"

DATABASES = {
    "default": dj_database_url.parse(DJANGO_DB_URL),
}


# Default primary key field type
# https://docs.djangoproject.com/en/dev/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Password hashers
# https://docs.djangoproject.com/en/dev/ref/settings/#password-hashers

# Use the simple MD5PasswordHasher to speed up test times.
# Warning: The MD5PasswordHasher is unsafe for production!
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.MD5PasswordHasher",
]


# Miscellaneous authentication settings
# https://docs.djangoproject.com/en/dev/ref/settings/


LOGIN_REDIRECT_URL = reverse_lazy("core:home")
LOGOUT_REDIRECT_URL = reverse_lazy("login")


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = "en-us"
# LANGUAGE_CODE = "nl-nl"
# LANGUAGE_CODE = "he"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

# For `Plural-Forms` in `.po` files:
# https://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"


# Media files
# https://docs.djangoproject.com/en/4.2/topics/files/

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"


# Django Silk
# https://github.com/jazzband/django-silk/tree/master/silk

SILKY_AUTHORISATION = True
SILKY_INTERCEPT_PERCENT = 100
SILKY_META = True
SILKY_PYTHON_PROFILER_RESULT_PATH = MEDIA_ROOT / "_profiles"

# Toggle Silk:
SILKY_PYTHON_PROFILER = ENABLE_SILKY
SILKY_PYTHON_PROFILER_BINARY = ENABLE_SILKY
