# Generated by Django 6.2.dev20260901201541 on 2026-09-02 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TodoList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=32, verbose_name="title")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
            ],
            options={
                "verbose_name": "to-do list",
                "verbose_name_plural": "to-do lists",
                "indexes": [models.Index(fields=["created_at"], name="todo_list_created_at_idx")],
            },
        ),
        migrations.CreateModel(
            name="TodoItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(verbose_name="description")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="completed at")),
                (
                    "is_done",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(completed_at__isnull=False, then=models.Value(True)),
                            default=models.Value(False),
                            output_field=models.BooleanField(),
                        ),
                        output_field=models.BooleanField(),
                        verbose_name="is done",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "todo_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="todo.todolist",
                        verbose_name="to-do list",
                    ),
                ),
            ],
            options={
                "verbose_name": "to-do item",
                "verbose_name_plural": "to-do items",
                "indexes": [
                    models.Index(fields=["completed_at"], name="todo_todoitem_completed_at_idx"),
                    models.Index(fields=["created_at"], name="todo_todoitem_created_at_idx"),
                    models.Index(fields=["is_done"], name="todo_todoitem_is_done_idx"),
                ],
            },
        ),
    ]
