# Generated by Django 6.0.dev20250403155126 on 2025-05-19 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extradata",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extra_data",
                to="people.person",
                verbose_name="person",
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_links",
                to="people.person",
                verbose_name="person",
            ),
        ),
    ]
